version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    restart: unless-stopped
    image: felddy/foundryvtt:release
    hostname: hostname
    volumes:
      - type: bind
        source: ./Data
        target: /data
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json